# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push and pull request events but only for pull_requests on the main branch
  # push:
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        required: true
        default: 'ubuntu-20.04'
        type: choice
        options:
          - 'macos-latest'
          - 'ubuntu-20.04'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "build_linux and build_macos"
  build_linux:
    if: ${{ (github.event.inputs.os == '') || (github.event.inputs.os == 'ubuntu-20.04') }}
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: update chrome to latest stable
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: copy files
        run: |
            cp $GITHUB_WORKSPACE/config/database.yml.actions $GITHUB_WORKSPACE/config/database.yml
            cp $GITHUB_WORKSPACE/Kitodo-DataManagement/src/main/resources/db/config/flyway.properties.actions $GITHUB_WORKSPACE/Kitodo-DataManagement/src/main/resources/db/config/flyway.properties

      # Runs a set of commands using the runners shell
      - name: start mysql
        run:
            sudo service mysql start
      - name: check MySQL version
        run:
            mysql --version
      - name: create database
        run:
            mysql -u root -proot -e 'CREATE DATABASE kitodo;'
      - name: setup database
        run: |
            mysql -u root -proot -e "CREATE USER 'kitodo'@'localhost' IDENTIFIED BY 'kitodo';"
            mysql -u root -proot -e "GRANT ALL ON kitodo.* TO 'kitodo'@'localhost';"
      - name: import schema
        run:
            mysql -u root -proot kitodo < $GITHUB_WORKSPACE/Kitodo/setup/schema.sql
      - name: import default
        run:
            mysql -u root -proot kitodo < $GITHUB_WORKSPACE/Kitodo/setup/default.sql
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: check java version
        run:
            java --version
      - name: check maven version
        run:
            mvn --version
      - name: run build
        run:
            mvn clean install -B '-Pall-tests,flyway,checkstyle,!development' && xvfb-run --server-args="-screen 0 1600x1280x24" mvn clean install -B '-Pselenium,!development'

  build_macos:
    if: ${{ (github.event.inputs.os == 'macos-latest') }}
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: update chrome to latest stable
      #  run: |
      #      brew list
      #      brew install chromium
      - name: set up MariaDB, JDK 11 and Tomcat 9
        run:
            brew install mariadb openjdk@11 tomcat@9

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: copy files
        run: |
            cp $GITHUB_WORKSPACE/config/database.yml.actions $GITHUB_WORKSPACE/config/database.yml
            cp $GITHUB_WORKSPACE/Kitodo-DataManagement/src/main/resources/db/config/flyway.properties.actions $GITHUB_WORKSPACE/Kitodo-DataManagement/src/main/resources/db/config/flyway.properties

      # Runs a set of commands using the runners shell
      - name: start MariaDB
        run: |
            brew services start mariadb
            brew services
      - name: check MariaDB version
        run: |
            brew services
            mariadb --version
      - name: create and setup database
        run: |
            brew services
            mariadb -e 'CREATE DATABASE kitodo;'
            mariadb -e "CREATE USER 'kitodo'@'localhost' IDENTIFIED BY 'kitodo';"
            mariadb -e "GRANT ALL ON kitodo.* TO 'kitodo'@'localhost';"
      - name: import schema
        run:
            mariadb kitodo < $GITHUB_WORKSPACE/Kitodo/setup/schema.sql
      - name: import default
        run:
            mariadb kitodo < $GITHUB_WORKSPACE/Kitodo/setup/default.sql
      - name: check java version
        run:
            java --version
      - name: check maven version
        run:
            mvn --version
      - name: run build
        run:
            mvn clean install -B '-Pall-tests,flyway,checkstyle,!development' && xvfb-run --server-args="-screen 0 1600x1280x24" mvn clean install -B '-Pselenium,!development'
